name: Build and Deploy

on:
  push:
    branches: [main]
    paths:
      - 'web/**'
      - 'Dockerfile'
      - 'docker-compose.prod.yml'
      - 'php-prod.ini'
      - '.github/workflows/build.yml'
  workflow_dispatch:

env:
  REGISTRY: registry.digitalocean.com
  IMAGE_NAME: wp-ead-rio

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to DigitalOcean Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ secrets.DO_REGISTRY_TOKEN }}
        password: ${{ secrets.DO_REGISTRY_TOKEN }}

    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ secrets.DO_REGISTRY_NAME }}/${{ env.IMAGE_NAME }}
        tags: |
          type=ref,event=branch
          type=sha,prefix={{branch}}-
          type=raw,value=latest,enable={{is_default_branch}}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Output image tags
      run: |
        echo "Built and pushed image with tags:"
        echo "${{ steps.meta.outputs.tags }}"

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: success()

    steps:
    - name: Deploy to DigitalOcean Droplet
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.DO_HOST }}
        username: ${{ secrets.DO_USERNAME }}
        key: ${{ secrets.DO_SSH_KEY }}
        port: ${{ secrets.DO_PORT || '22' }}
        script: |
          # Set the Docker image with registry path
          export DOCKER_IMAGE="${{ env.REGISTRY }}/${{ secrets.DO_REGISTRY_NAME }}/${{ env.IMAGE_NAME }}:latest"

          # Create and navigate to project directory
          sudo mkdir -p /opt/wp-ead-rio
          cd /opt/wp-ead-rio

          # Download docker-compose.prod.yml if it doesn't exist
          if [ ! -f docker-compose.prod.yml ]; then
            curl -o docker-compose.prod.yml https://raw.githubusercontent.com/${{ github.repository }}/main/docker-compose.prod.yml
          fi

          # Download PHP production configuration if it doesn't exist
          if [ ! -f php-prod.ini ]; then
            curl -o php-prod.ini https://raw.githubusercontent.com/${{ github.repository }}/main/php-prod.ini
          fi

          # Create .env file if it doesn't exist
          if [ ! -f .env ]; then
            cat > .env << EOF
          DOCKER_IMAGE=$DOCKER_IMAGE
          DB_NAME=wp_ead_rio
          DB_USER=wp_user
          DB_PASSWORD=${{ secrets.DB_PASSWORD }}
          DB_ROOT_PASSWORD=${{ secrets.DB_ROOT_PASSWORD }}
          TABLE_PREFIX=wp_
          WP_DEBUG=false
          EOF
          fi

          # Login to DigitalOcean Container Registry
          echo "Logging into container registry..."
          echo "${{ secrets.DO_REGISTRY_TOKEN }}" | docker login registry.digitalocean.com -u "${{ secrets.DO_REGISTRY_TOKEN }}" --password-stdin

          # Pull the latest image
          echo "Pulling latest Docker image: $DOCKER_IMAGE"
          if ! docker pull $DOCKER_IMAGE; then
            echo "Failed to pull Docker image. Check registry access and image name."
            exit 1
          fi

          # Update the running containers
          echo "Updating containers..."
          if ! docker-compose -f docker-compose.prod.yml up -d --no-deps wordpress; then
            echo "Failed to update containers. Check docker-compose.prod.yml and .env file."
            exit 1
          fi

          # Clean up old images
          echo "Cleaning up old images..."
          docker image prune -f

          echo "Deployment completed successfully!"

    - name: Verify deployment
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.DO_HOST }}
        username: ${{ secrets.DO_USERNAME }}
        key: ${{ secrets.DO_SSH_KEY }}
        port: ${{ secrets.DO_PORT || '22' }}
        script: |
          cd /opt/wp-ead-rio
          echo "Checking container status..."
          docker-compose -f docker-compose.prod.yml ps

          echo "Checking WordPress health..."
          docker-compose -f docker-compose.prod.yml exec -T wordpress wp --version || echo "WordPress CLI not available"